sudo: required
services:
  - docker

before_install:
  - docker build -t avidocker001/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true avidocker001/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t avidocker001/multi-client ./client
  - docker build -t avidocker001/multi-nginx ./nginx
  - docker build -t avidocker001/multi-api ./server
  - docker build -t avidocker001/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push avidocker001/multi-client
  - docker push avidocker001/multi-nginx
  - docker push avidocker001/multi-api
  - docker push avidocker001/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket: "elasticbeanstalk-ap-south-1-261643621708"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
